spring.application.name=development
spring.datasource.url=jdbc:postgresql://db.utakkguinknzfwnexuxj.supabase.co/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}